load 'environment.rb'
task :store_in_memory do
  InsertKeysToRedis.kickoff
end

task :check_known_unknowns do
  
end

task :check_unknown_unknowns do
  ParseSubmissionIdSpace.kickoff
  ParseCommentIdSpace.kickoff
end