load 'environment.rb'
task :download_baumgartner do
  Download.new.download_all
end

task :store_in_memory do
  InsertKeysToRedis.kickoff
end

task :check_known_unknowns do
  ParseSourceFile.kickoff
end

task :check_unknown_unknowns do
  ParseSubmissionIdSpace.kickoff
  ParseCommentIdSpace.kickoff
end